#!/bin/sh
# 1. 清除默认冗余规则
uci delete firewall.@rule[0] 2>/dev/null
uci delete firewall.@rule[1] 2>/dev/null

# 2. 允许LAN内部所有流量
uci set firewall.@rule[0]='rule'
uci set firewall.@rule[0].name='Allow-LAN-All'
uci set firewall.@rule[0].src='lan'
uci set firewall.@rule[0].dest='*'
uci set firewall.@rule[0].target='ACCEPT'

# 3. 允许WAN→LAN的回应流量（如5G拨号后的HTTP/HTTPS）
uci set firewall.@rule[1]='rule'
uci set firewall.@rule[1].name='Allow-WAN-Reply'
uci set firewall.@rule[1].src='wan'
uci set firewall.@rule[1].dest='lan'
uci set firewall.@rule[1].proto='tcp udp'
uci set firewall.@rule[1].ctstate='ESTABLISHED,RELATED'
uci set firewall.@rule[1].target='ACCEPT'

# 4. 允许5G模组的QMI/MBIM控制流量
uci set firewall.@rule[2]='rule'
uci set firewall.@rule[2].name='Allow-5G-Control'
uci set firewall.@rule[2].src='*'
uci set firewall.@rule[2].dest='*'
uci set firewall.@rule[2].proto='udp tcp'
uci set firewall.@rule[2].dest_port='53 67 68'  # DNS+DHCP端口（5G拨号需）
uci set firewall.@rule[2].target='ACCEPT'

# 5. 禁用WAN口Ping（增强安全性）
uci set firewall.@rule[3]='rule'
uci set firewall.@rule[3].name='Deny-WAN-Ping'
uci set firewall.@rule[3].src='wan'
uci set firewall.@rule[3].proto='icmp'
uci set firewall.@rule[3].icmp_type='echo-request'
uci set firewall.@rule[3].target='DROP'

# 6. 提交配置并重启防火墙
uci commit firewall
/etc/init.d/firewall restart
