name: Build iStoreOS for RK3568 with QWRT 5G

on:
  push:
    branches: [ main ]
    paths:
      - '.config'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libncursesw5-dev libssl-dev libelf-dev python3-distutils rsync unzip zlib1g-dev file wget libusb-1.0-0-dev

      - name: Clone iStoreOS source
        run: |
          git clone https://github.com/istoreos/istoreos.git --depth=1 --branch=main istoreos-src
          cd istoreos-src

      - name: Manual clone QWRT and Quectel feeds (bypass HTTPS auth issue)
        run: |
          cd istoreos-src
          # 创建feeds目录（如果不存在）
          mkdir -p feeds/qwrt feeds/quectel
          # 手动克隆QWRT仓库（使用HTTPS，强制公开访问）
          git clone https://github.com/qwrt-project/qwrt-packages.git --depth=1 feeds/qwrt
          # 手动克隆广和通仓库
          git clone https://github.com/quectel/quectel-openwrt.git --depth=1 feeds/quectel
          # 确保feeds配置中包含这两个仓库（避免后续脚本忽略）
          echo "src-link qwrt feeds/qwrt" >> feeds.conf.default
          echo "src-link quectel feeds/quectel" >> feeds.conf.default

      - name: Load custom config
        run: |
          cp ./.config istoreos-src/.config
          cd istoreos-src
          # 确保5G模组必要配置
          echo "CONFIG_PACKAGE_kmod-usb-serial=y" >> .config
          echo "CONFIG_PACKAGE_kmod-usb-serial-qcserial=y" >> .config  # 高通串口驱动
          echo "CONFIG_PACKAGE_kmod-qmi-wwan=y" >> .config  # QMI协议
          echo "CONFIG_PACKAGE_kmod-usb-net-qmi-wwan=y" >> .config
          echo "CONFIG_PACKAGE_modemmanager=y" >> .config
          echo "CONFIG_PACKAGE_modemmanager-ppp=y" >> .config
          echo "CONFIG_PACKAGE_luci-proto-qmi=y" >> .config
          echo "CONFIG_PACKAGE_qmi-utils=y" >> .config
          echo "CONFIG_PACKAGE_uqmi=y" >> .config
          echo "CONFIG_PACKAGE_qwrt-modem=y" >> .config
          echo "CONFIG_PACKAGE_qwrt-modem-quectel=y" >> .config

      - name: Copy custom files
        run: |
          cp -r ./files istoreos-src/
          mkdir -p istoreos-src/files/etc/modprobe.d/
          echo "options qcserial vendor=0x05c6 product=0x90b2" > istoreos-src/files/etc/modprobe.d/fm35ogl.conf  # FM35OGL的VID/PID

      - name: Update and install feeds (with manual clones)
        run: |
          cd istoreos-src
          ./scripts/feeds update -a  # 此时qwrt和quectel已手动克隆，仅更新其他源
          ./scripts/feeds install -a  # 安装所有包（包括手动克隆的）

      - name: Build firmware
        run: |
          cd istoreos-src
          make -j$(nproc) defconfig
          make -j$(nproc) download V=s
          make -j$(nproc) V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: istoreos-rk3568-5g-firmware
          path: istoreos-src/bin/targets/rockchip/armv8/*.img
