name: Build iStoreOS for RK3568 (Correct Package Name)
on:
  push:
    branches: [ main ]
    paths:
      - '.config'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install correct elftools package
        run: |
          sudo apt update
          # 尝试不同的包名
          sudo apt install -y python3-pyelftools || \
          sudo apt install -y python3-elftools || \
          pip3 install pyelftools
          
          # 验证
          python3 -c "import elftools; print('成功导入elftools')"

      - name: Install base deps
        run: |
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev \
            libncursesw5-dev libssl-dev libelf-dev python3 python3-pip \
            rsync unzip zlib1g-dev file wget

      - name: Clone and build
        run: |
          git clone https://github.com/istoreos/istoreos.git --depth=1 --branch=istoreos-24.10 istoreos-src
          git clone https://github.com/Siriling/5G-Modem-Support.git --depth=1 5G-Modem-Support
          
          cd istoreos-src
          [ -f ../.config ] && cp ../.config .config || true
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make download
          make -j$(nproc) V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: istoreos-src/bin/targets/rockchip/armv8/*.img
