name: Build iStoreOS for xgp (RK3568) with 5G-Modem-Support

on:
  push:
    branches: [ main ]
    paths:
      - '.config'  # 仅修改.config时触发编译
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      # 限制日志输出大小，防止中断（单个日志文件最大50MB，超过自动切割）
      MAX_LOG_SIZE: "52428800"  # 50MB（字节）

    steps:
      - name: Checkout local code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          # 安装编译依赖，增加日志切割工具logrotate
          sudo apt update -y && sudo apt upgrade -y
          sudo apt install -y \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libncursesw5-dev libssl-dev libelf-dev \
            python3-distutils rsync unzip zlib1g-dev file wget logrotate
          # 配置logrotate限制编译日志大小
          echo "/tmp/build-istoreos.log {
            size ${MAX_LOG_SIZE}
            rotate 5
            compress
            missingok
            notifempty
          }" | sudo tee /etc/logrotate.d/istoreos-build

      - name: Clone iStoreOS source
        run: |
          git clone https://github.com/istoreos/istoreos.git --depth=1 --branch=main istoreos-src
          cd istoreos-src
          # 克隆5G-Modem-Support仓库到package目录（替换原生5G驱动）
          git clone https://github.com/Siriling/5G-Modem-Support.git \
            package/5G-Modem-Support --depth=1

      - name: Load custom config
        run: |
          # 复制自定义.config到源码目录（已替换5G驱动配置）
          cp ./.config istoreos-src/.config
          # 复制自定义files（如有），无则可删除此步骤
          if [ -d "./files" ]; then
            cp -r ./files istoreos-src/
          fi

      - name: Update and install feeds
        run: |
          cd istoreos-src
          # 更新feeds并安装所有包（含5G-Modem-Support）
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          # 确保5G-Modem-Support包被正确识别
          echo "Checking 5G-Modem-Support package..."
          if [ -d "package/5G-Modem-Support" ]; then
            echo "5G-Modem-Support package loaded successfully"
          else
            echo "Error: 5G-Modem-Support package not found!" && exit 1
          fi

      - name: Build firmware (with log limit)
        run: |
          cd istoreos-src
          # 生成配置并编译，日志重定向到文件并通过logrotate限制大小
          make -j$(nproc) defconfig 2>&1 | tee -a /tmp/build-istoreos.log
          make -j$(nproc) download V=s 2>&1 | tee -a /tmp/build-istoreos.log
          # 手动触发logrotate确保日志不超限
          sudo logrotate -f /etc/logrotate.d/istoreos-build
          make -j$(nproc) V=s 2>&1 | tee -a /tmp/build-istoreos.log
          # 再次触发logrotate处理最终日志
          sudo logrotate -f /etc/logrotate.d/istoreos-build

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: istoreos-xgp-rk3568-firmware
          path: |
            istoreos-src/bin/targets/rockchip/armv8/*.img
            istoreos-src/bin/targets/rockchip/armv8/*.tar.gz
          retention-days: 7  # 固件保留7天，可按需调整

      - name: Upload build log (for debug)
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: /tmp/build-istoreos.log*
          retention-days: 3  # 日志保留3天
