name: iStoreOS for XGP Build (FM350GL Support)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      BUILD_TIMEOUT: 1800
      BUILD_LOG_LIMIT: 1000000  # 限制日志大小1MB

    steps:
    - name: Checkout iStoreOS source
      uses: actions/checkout@v4
      with:
        ref: main
        path: iStoreOS

    - name: Checkout QModem
      uses: actions/checkout@v4
      with:
        repository: FUjr/QModem
        ref: main
        path: QModem

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev zlib1g-dev gawk git wget curl subversion libssl-dev libelf-dev libxml2-dev libxslt1-dev python3 python3-pip python3-setuptools python3-venv python3-dev libffi-dev libexpat1-dev liblz4-tool liblzo2-dev libzstd-dev libunwind8 libunwind-dev libtinfo5 libtinfo-dev libcap-dev libcap-ng-dev libseccomp-dev libmnl-dev libnl-genl-3-dev libnl-route-3-dev

    - name: Setup build environment
      run: |
        cd iStoreOS
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        mkdir -p ./target/linux/rockchip/patches
        cp -r ../QModem/patches/* ./target/linux/rockchip/patches/
        
        # 添加FM350GL专属配置
        echo "CONFIG_PACKAGE_modemmanager-with-mbim=y" >> ../config.txt
        echo "CONFIG_PACKAGE_modemmanager-with-qrtr=y" >> ../config.txt
        echo "CONFIG_PACKAGE_kmod-qrtr=y" >> ../config.txt
        echo "CONFIG_PACKAGE_kmod-qrtr-mhi=y" >> ../config.txt
        echo "CONFIG_PACKAGE_kmod-mhi-bus=y" >> ../config.txt
        echo "CONFIG_PACKAGE_kmod-mhi-net=y" >> ../config.txt
        echo "CONFIG_PACKAGE_kmod-mhi-wwan-ctrl=y" >> ../config.txt
        echo "CONFIG_PACKAGE_luci-app-wifi-hotspot=y" >> ../config.txt
        echo "CONFIG_PACKAGE_luci-app-modemmanager=y" >> ../config.txt

    - name: Copy FM350GL USB IDs
      run: |
        cd iStoreOS
        mkdir -p files/etc
        cp ../QModem/usb.ids files/etc/  # 包含FM350GL的USB ID (19d2:0001)
        echo "CONFIG_PACKAGE_base-files-etc=y" >> .config

    - name: Apply config
      run: |
        cd iStoreOS
        cp ../config.txt .config
        make defconfig
        echo "CONFIG_TARGET_ROOTFS_PARTSIZE=256" >> .config
        echo "CONFIG_TARGET_KERNEL_PARTSIZE=64" >> .config

    - name: Build iStoreOS
      run: |
        cd iStoreOS
        # 添加防止日志过大的关键参数
        make -j$(nproc) V=s | tee build.log | head -c ${{ env.BUILD_LOG_LIMIT }}
        if [ ! -f bin/targets/rockchip/armv8/xgp/squashfs-sysupgrade.bin ]; then
          echo "Build failed"
          exit 1
        fi

    - name: Verify build artifacts
      run: |
        cd iStoreOS
        ls -lh bin/targets/rockchip/armv8/xgp/
        file bin/targets/rockchip/armv8/xgp/squashfs-sysupgrade.bin

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: iStoreOS-XGP-FM350GL
        path: iStoreOS/bin/targets/rockchip/armv8/xgp/squashfs-sysupgrade.bin
        retention-days: 30

    - name: Upload build log
      uses: actions/upload-artifact@v3
      with:
        name: build-log
        path: iStoreOS/build.log
        retention-days: 30
