name: Build iStoreOS for RK3568 with 5G Modem Support

on:
  push:
    branches: [ main ]
    paths:
      - '.config'
      - 'files/**'
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      clean_build:
        description: 'Clean build (remove previous build files)'
        required: false
        default: false
        type: boolean

env:
  BUILD_DIR: istoreos-src
  MAX_JOBS: 4  # 限制并行任务数防止内存溢出

jobs:
  build:
    runs-on: ubuntu-22.04
    
    strategy:
      matrix:
        include:
          - device: nlnet_xgp
            target: rockchip/armv8

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup swap space (防止内存溢出)
      run: |
        sudo fallocate -l 4G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        free -h

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses5-dev libncursesw5-dev libssl-dev libelf-dev \
          python3-distutils rsync unzip zlib1g-dev file wget \
          cmake pkg-config libtool automake autoconf \
          subversion mercurial time

    - name: Clone iStoreOS source
      run: |
        git clone https://github.com/istoreos/istoreos.git $BUILD_DIR --depth=1 --branch=istoreos-24.10
        cd $BUILD_DIR

    - name: Clone 5G-Modem-Support
      run: |
        cd $BUILD_DIR
        git clone https://github.com/Siriling/5G-Modem-Support.git package/5g-modem-support
        # 添加5G模块到feeds
        echo "src-git modem_support https://github.com/Siriling/5G-Modem-Support.git" >> feeds.conf.default

    - name: Clean previous build (可选)
      if: inputs.clean_build == true
      run: |
        cd $BUILD_DIR
        make clean

    - name: Load custom config
      run: |
        cp .config $BUILD_DIR/.config

    - name: Copy custom files
      run: |
        cp -rf files/* $BUILD_DIR/files/ 2>/dev/null || true

    - name: Update and install feeds
      run: |
        cd $BUILD_DIR
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        # 特别安装5G相关包
        ./scripts/feeds install quectel-cm-5g quectel_Gobinet quectel_MHI modemmanager

    - name: Configure build
      run: |
        cd $BUILD_DIR
        make defconfig
        # 应用我们的自定义配置
        scripts/diffconfig.sh > config_diff
        cat config_diff

    - name: Download sources (限制内存使用)
      run: |
        cd $BUILD_DIR
        # 限制并行下载和编译任务数
        make -j2 download V=sc 2>&1 | head -1000
        echo "Download completed"

    - name: Build toolchain (分步构建减少内存压力)
      run: |
        cd $BUILD_DIR
        make -j$MAX_JOBS toolchain/install V=s 2>&1 | tail -500

    - name: Build kernel (分步构建)
      run: |
        cd $BUILD_DIR
        make -j$MAX_JOBS target/compile V=s 2>&1 | tail -1000

    - name: Build packages (分步构建)
      run: |
        cd $BUILD_DIR
        make -j$MAX_JOBS package/compile V=s 2>&1 | tail -1500

    - name: Build firmware image
      run: |
        cd $BUILD_DIR
        make -j$MAX_JOBS V=s 2>&1 | tail -2000

    - name: Check build artifacts
      run: |
        cd $BUILD_DIR
        find bin/targets -name "*.img" -o -name "*.gz" | head -10
        du -sh bin/targets/*

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: istoreos-rk3568-5g-firmware
        path: ${{ env.BUILD_DIR }}/bin/targets/rockchip/armv8/*.img.gz
        retention-days: 30

    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          ${{ env.BUILD_DIR }}/logs/
          ${{ env.BUILD_DIR }}/build.log
        retention-days: 7

    - name: Cleanup swap
      if: always()
      run: |
        sudo swapoff /swapfile || true
        sudo rm -f /swapfile || true
