name: Build iStoreOS for RK3568 with 5G (FM35OGL)

on:
  push:
    branches: [ main ]
    paths:
      - '.config'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libncursesw5-dev libssl-dev libelf-dev python3-distutils rsync unzip zlib1g-dev file wget libusb-1.0-0-dev

      - name: Clone iStoreOS source
        run: |
          git clone https://github.com/istoreos/istoreos.git --depth=1 --branch=main istoreos-src
          cd istoreos-src

      - name: 清理所有自定义源（仅保留默认源）
        run: |
          cd istoreos-src
          # 恢复iStoreOS默认feeds配置，不添加任何第三方源
          git checkout feeds.conf.default  # 用源码自带的默认配置

      - name: Load custom config (仅依赖默认组件)
        run: |
          cp ./.config istoreos-src/.config
          cd istoreos-src
          # 强制启用FM35OGL所需的核心组件（均来自OpenWRT默认源）
          sed -i '/CONFIG_PACKAGE_kmod-usb-serial/d' .config && echo "CONFIG_PACKAGE_kmod-usb-serial=y" >> .config
          sed -i '/CONFIG_PACKAGE_kmod-usb-serial-qcserial/d' .config && echo "CONFIG_PACKAGE_kmod-usb-serial-qcserial=y" >> .config  # 高通串口驱动（FM35OGL核心依赖）
          sed -i '/CONFIG_PACKAGE_kmod-qmi-wwan/d' .config && echo "CONFIG_PACKAGE_kmod-qmi-wwan=y" >> .config  # QMI协议驱动
          sed -i '/CONFIG_PACKAGE_kmod-usb-net-qmi-wwan/d' .config && echo "CONFIG_PACKAGE_kmod-usb-net-qmi-wwan=y" >> .config
          sed -i '/CONFIG_PACKAGE_modemmanager/d' .config && echo "CONFIG_PACKAGE_modemmanager=y" >> .config  # 调制解调器管理
          sed -i '/CONFIG_PACKAGE_modemmanager-ppp/d' .config && echo "CONFIG_PACKAGE_modemmanager-ppp=y" >> .config
          sed -i '/CONFIG_PACKAGE_luci-proto-qmi/d' .config && echo "CONFIG_PACKAGE_luci-proto-qmi=y" >> .config  # LuCI配置界面
          sed -i '/CONFIG_PACKAGE_qmi-utils/d' .config && echo "CONFIG_PACKAGE_qmi-utils=y" >> .config  # QMI调试工具
          sed -i '/CONFIG_PACKAGE_uqmi/d' .config && echo "CONFIG_PACKAGE_uqmi=y" >> .config  # 轻量QMI客户端
          sed -i '/CONFIG_PACKAGE_luci-app-modemmanager/d' .config && echo "CONFIG_PACKAGE_luci-app-modemmanager=y" >> .config  # 图形化管理界面

      - name: 配置FM35OGL专用识别规则
        run: |
          cd istoreos-src
          # 添加模组USB VID/PID识别（确保系统正确识别硬件）
          mkdir -p files/etc/udev/rules.d/
          echo 'SUBSYSTEM=="tty", ATTRS{idVendor}=="05c6", ATTRS{idProduct}=="90b2", SYMLINK+="ttyUSB_FM35OGL", MODE="0666"' > files/etc/udev/rules.d/99-fm35ogl.rules
          # 配置modprobe加载参数
          mkdir -p files/etc/modprobe.d/
          echo "options qcserial vendor=0x05c6 product=0x90b2" > files/etc/modprobe.d/fm35ogl.conf

      - name: 更新并安装默认feeds（无第三方源，避免冲突）
        run: |
          cd istoreos-src
          ./scripts/feeds update -a  # 仅更新iStoreOS默认源
          ./scripts/feeds install -a

      - name: 编译固件
        run: |
          cd istoreos-src
          make -j$(nproc) defconfig
          make -j$(nproc) download V=s
          make -j$(nproc) V=s

      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: istoreos-rk3568-fm35ogl-firmware
          path: istoreos-src/bin/targets/rockchip/armv8/*.img
