name: Build iStoreOS for RK3568 with QWRT 5G

on:
  push:
    branches: [ main ]
    paths:
      - '.config'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libncursesw5-dev libssl-dev libelf-dev python3-distutils rsync unzip zlib1g-dev file wget libusb-1.0-0-dev

      - name: Clone iStoreOS source
        run: |
          git clone https://github.com/istoreos/istoreos.git --depth=1 --branch=main istoreos-src
          cd istoreos-src

      - name: Add QWRT 5G support feeds (SSH protocol)
        run: |
          cd istoreos-src
          # 关键修改：将 HTTPS 链接替换为 SSH 链接，避免认证问题
          echo "src-git qwrt git@github.com:qwrt-project/qwrt-packages.git" >> feeds.conf.default
          echo "src-git quectel git@github.com:quectel/quectel-openwrt.git" >> feeds.conf.default

      - name: Load custom config
        run: |
          cp ./.config istoreos-src/.config
          cd istoreos-src
          # 确保必要的5G模组配置
          echo "CONFIG_PACKAGE_kmod-usb-serial=y" >> .config
          echo "CONFIG_PACKAGE_kmod-usb-serial-qcserial=y" >> .config
          echo "CONFIG_PACKAGE_kmod-qmi-wwan=y" >> .config
          echo "CONFIG_PACKAGE_kmod-usb-net-qmi-wwan=y" >> .config
          echo "CONFIG_PACKAGE_modemmanager=y" >> .config
          echo "CONFIG_PACKAGE_modemmanager-ppp=y" >> .config
          echo "CONFIG_PACKAGE_luci-proto-qmi=y" >> .config
          echo "CONFIG_PACKAGE_qmi-utils=y" >> .config
          echo "CONFIG_PACKAGE_uqmi=y" >> .config
          echo "CONFIG_PACKAGE_qwrt-modem=y" >> .config
          echo "CONFIG_PACKAGE_qwrt-modem-quectel=y" >> .config

      - name: Copy custom files
        run: |
          cp -r ./files istoreos-src/
          mkdir -p istoreos-src/files/etc/modprobe.d/
          echo "options qcserial vendor=0x05c6 product=0x90b2" > istoreos-src/files/etc/modprobe.d/fm35ogl.conf

      - name: Update and install feeds
        run: |
          cd istoreos-src
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build firmware
        run: |
          cd istoreos-src
          make -j$(nproc) defconfig
          make -j$(nproc) download V=s
          make -j$(nproc) V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: istoreos-rk3568-5g-firmware
          path: istoreos-src/bin/targets/rockchip/armv8/*.img
