name: Build iStoreOS for RK3568

on:
  push:
    branches: [ main ]
    paths:
      - '.config'  # 只有修改.config时才触发编译
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-22.04  # 使用Ubuntu 22.04环境

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

      - name: Clone iStoreOS source
        run: |
          git clone https://github.com/istoreos/istoreos.git --depth=1 --branch=main istoreos-src
          cd istoreos-src

      - name: Load custom config
        run: |
          cp ./.config istoreos-src/.config  # 复制我们的配置文件到源码目录

      - name: Update and install feeds
        run: |
          cd istoreos-src
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build firmware
        run: |
          cd istoreos-src
          make -j$(nproc) defconfig  # 生成默认配置
          make -j$(nproc) download V=s  # 下载依赖包
          make -j$(nproc) V=s  # 编译（-j后面是线程数，nproc自动获取CPU核心数）

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: istoreos-rk3568-firmware
          path: istoreos-src/bin/targets/rockchip/armv8/*.img  # 编译产物路径（RK3568属于armv8）
