# 【彻底修复】Copy LUCI管理界面（hypermodem）- 解决目录不存在问题
- name: Copy LUCI management interface (luci-app-hypermodem)
  run: |
    # 1. 定义iStoreOS LUCI应用的官方标准目录（关键：使用applications而非apps）
    TARGET_DIR="istoreos-src/package/luci/applications"
    
    # 2. 先验证iStoreOS源码的LUCI目录是否存在（排查源码拉取是否正常）
    if [ ! -d "istoreos-src/package/luci" ]; then
      echo "❌ 错误：iStoreOS源码的LUCI目录（istoreos-src/package/luci）不存在！"
      echo "请检查前序步骤中iStoreOS源码克隆是否成功（git clone istoreos）"
      exit 1
    fi
    echo "✅ iStoreOS LUCI基础目录已存在：istoreos-src/package/luci"
    
    # 3. 强制创建目标目录（-p参数：即使父目录不存在也自动创建，避免“目录不存在”错误）
    mkdir -p "$TARGET_DIR"
    if [ -d "$TARGET_DIR" ]; then
      echo "✅ 已成功创建LUCI应用目标目录：$TARGET_DIR"
    else
      echo "❌ 无法创建目标目录：$TARGET_DIR（可能是权限问题）"
      exit 1
    fi
    
    # 4. 复制luci-app-hypermodem到标准目录
    cp -r 5G-Modem-Support/luci-app-hypermodem "$TARGET_DIR/"
    
    # 5. 复制后校验（确保文件真的复制成功，避免静默失败）
    if [ -d "$TARGET_DIR/luci-app-hypermodem" ]; then
      echo "✅ luci-app-hypermodem 已成功复制到：$TARGET_DIR/luci-app-hypermodem"
      # 可选：查看复制后的目录结构，确认文件完整性
      echo "🔍 复制后的目录结构："
      ls -l "$TARGET_DIR/luci-app-hypermodem"
    else
      echo "❌ luci-app-hypermodem 复制失败！目标目录中未找到该文件夹"
      exit 1
    fi

# （可选）若需要短信功能，添加以下步骤（同样使用标准目录）
# - name: Copy SMS tool (luci-app-sms-tool)
#   run: |
#     TARGET_DIR="istoreos-src/package/luci/applications"
#     mkdir -p "$TARGET_DIR"
#     cp -r 5G-Modem-Support/luci-app-sms-tool "$TARGET_DIR/"
#     if [ -d "$TARGET_DIR/luci-app-sms-tool" ]; then
#       echo "✅ luci-app-sms-tool 复制完成"
#     else
#       echo "❌ luci-app-sms-tool 复制失败"
#       exit 1
#     fi
