- name: Build firmware (fixed terminal & dependency)
  run: |
    cd istoreos-src
    # 修复终端环境+自动解决依赖
    export TERM=xterm
    make -j$(($(nproc)/2)) olddefconfig 2>&1 | tee ../$LOG_DIR/olddefconfig.log
    # 下载依赖包
    make -j$(($(nproc)/2)) download V=s 2>&1 | tee ../$LOG_DIR/download.log
    # 编译固件（限制线程避免日志过大）
    make -j$(($(nproc)/2)) V=s 2>&1 | tee ../$LOG_DIR/build.log

- name: Upload firmware (xgp device)
  uses: actions/upload-artifact@v4
  with:
    name: istoreos-xgp-firmware (RK3568 + 5G)
    path: |
      istoreos-src/bin/targets/${{ env.TARGET_ARCH }}/*.img
      istoreos-src/bin/targets/${{ env.TARGET_ARCH }}/*.tar.gz
    retention-days: 30

- name: Upload build logs (for debug)
  uses: actions/upload-artifact@v4
  with:
    name: istoreos-xgp-build-logs
    path: ${{ env.LOG_DIR }}/*.log
    retention-days: 14
