name: Build iStoreOS for RK3568 (Fixed elftools)
on:
  push:
    branches: [ main ]
    paths:
      - '.config'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install complete Python elftools environment
        run: |
          sudo apt update
          
          # 安装所有可能的Python elftools包
          sudo apt install -y python3-pyelftools python3-elftools || true
          
          # 如果系统包不可用，使用pip安装
          pip3 install pyelftools
          pip3 install --upgrade pip
          pip3 install setuptools wheel
          
          # 验证安装
          python3 -c "import elftools; print('elftools导入成功')"
          python3 -c "from elftools.elf.elffile import ELFFile; print('ELFFile导入成功')"
          
          # 检查Python路径
          python3 -c "import site; print('Python路径:', site.getsitepackages())"
          python3 -c "import elftools; print('elftools路径:', elftools.__file__)"

      - name: Install build dependencies
        run: |
          sudo apt install -y \
            build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git \
            libncurses5-dev libncursesw5-dev libssl-dev \
            libelf-dev python3 python3-pip python3-dev \
            rsync unzip zlib1g-dev file wget curl

      - name: Clone iStoreOS
        run: |
          git clone https://github.com/istoreos/istoreos.git --depth=1 --branch=istoreos-24.10 istoreos-src

      - name: Clone 5G-Modem-Support
        run: |
          git clone https://github.com/Siriling/5G-Modem-Support.git --depth=1 5G-Modem-Support

      - name: Setup Python environment for build
        run: |
          # 设置Python环境变量
          export PYTHONPATH=/usr/lib/python3/dist-packages:/usr/local/lib/python3.10/dist-packages
          echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
          
          # 验证编译环境能找到elftools
          cd istoreos-src
          python3 -c "import sys; sys.path.extend(['/usr/lib/python3/dist-packages', '/usr/local/lib/python3.10/dist-packages']); import elftools; print('编译环境elftools检查通过')"

      - name: Copy config and setup
        run: |
          cd istoreos-src
          [ -f ../.config ] && cp ../.config .config || true
          [ -d ../files ] && cp -r ../files . || true

      - name: Test prerequisite check
        run: |
          cd istoreos-src
          # 单独运行prereq检查，看具体错误
          make prereq || {
            echo "=== PREREQ检查失败详情 ==="
            # 尝试获取更详细的错误信息
            make V=s prereq 2>&1 | grep -A10 -B10 "elftools" || true
            exit 1
          }

      - name: Update feeds
        run: |
          cd istoreos-src
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build firmware
        run: |
          cd istoreos-src
          make defconfig
          make download
          make -j$(nproc) V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: istoreos-src/bin/targets/rockchip/armv8/*.img
