name: Build iStoreOS for RK3568 (with FM350GL 5G - Fixed LUCI Path)
on:
  push:
    branches: [ main ]
    paths:
      - '.config'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      ########################################################################
      # 1. 基础准备：拉取配置+安装依赖
      ########################################################################
      - name: Checkout local config
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev \
            libncursesw5-dev libssl-dev libelf-dev python3-distutils \
            rsync unzip zlib1g-dev file wget

      ########################################################################
      # 2. 拉取源码
      ########################################################################
      - name: Clone iStoreOS source
        run: |
          git clone https://github.com/istoreos/istoreos.git --depth=1 --branch=main istoreos-src
          cd istoreos-src
          if [ ! -d "package/luci" ]; then
            echo "❌ iStoreOS源码不完整，重新克隆"
            cd ..
            rm -rf istoreos-src
            git clone https://github.com/istoreos/istoreos.git --depth=1 --branch=main istoreos-src
          fi

      - name: Clone 5G-Modem-Support
        run: |
          git clone https://github.com/Siriling/5G-Modem-Support.git --depth=1 5G-Modem-Support

      ########################################################################
      # 3. 集成5G组件（修复路径问题）
      ########################################################################
      # 复制5G驱动
      - name: Copy FM350GL Drivers
        run: |
          mkdir -p istoreos-src/package/kernel/fibocom-drivers
          cp -r 5G-Modem-Support/fibocom_MHI istoreos-src/package/kernel/fibocom-drivers/
          cp -r 5G-Modem-Support/fibocom_QMI_WWAN istoreos-src/package/kernel/fibocom-drivers/

      # 复制拨号工具
      - name: Copy fibocom-dial
        run: |
          mkdir -p istoreos-src/package/network/utils/fibocom-dial
          cp -r 5G-Modem-Support/fibocom-dial/* istoreos-src/package/network/utils/fibocom-dial/

      # 复制LUCI界面（修复路径：使用applications而不是apps）
      - name: Copy luci-app-hypermodem
        run: |
          TARGET_DIR="istoreos-src/package/luci/applications"
          mkdir -p "$TARGET_DIR"
          cp -r 5G-Modem-Support/luci-app-hypermodem "$TARGET_DIR/"
          if [ -d "$TARGET_DIR/luci-app-hypermodem" ]; then
            echo "✅ luci-app-hypermodem复制成功"
          else
            echo "❌ 复制失败"
            exit 1
          fi

      ########################################################################
      # 4. 编译流程
      ########################################################################
      - name: Copy config and files
        run: |
          cp .config istoreos-src/.config
          [ -d ./files ] && cp -r ./files istoreos-src/ || echo "无自定义文件"

      - name: Update feeds
        run: |
          cd istoreos-src
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build firmware
        run: |
          cd istoreos-src
          make defconfig
          make download
          make -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: istoreos-rk3568-5g-firmware
          path: istoreos-src/bin/targets/rockchip/armv8/*.img
