name: Build iStoreOS for RK3568 (Simplified Stable Version)
on:
  push:
    branches: [ main ]
    paths:
      - '.config'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的Ubuntu版本
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libelf-dev libncurses5-dev \
            libncursesw5-dev libssl-dev python3 python3-distutils python3-setuptools \
            python3-pip python3-ply python3-yaml unzip wget rsync subversion \
            zlib1g-dev cmake curl libxml2-utils xsltproc

      - name: Clone iStoreOS
        run: |
          git clone https://github.com/istoreos/istoreos.git --depth=1 --branch=istoreos-24.10 istoreos-src

      - name: Clone 5G-Modem-Support
        run: |
          git clone https://github.com/Siriling/5G-Modem-Support.git --depth=1 5G-Modem-Support

      - name: Basic setup
        run: |
          cd istoreos-src
          [ -f ../.config ] && cp ../.config .config || true
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build with minimal flags
        run: |
          cd istoreos-src
          make defconfig
          make download
          make -j2
