name: 本地编译iStoreOS-XGP（最终稳定版）

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/local-build-final.yml'
      - 'xgp-qmodem.config'
      - 'files/**'

jobs:
  local-build:
    runs-on: self-hosted
    env:
      TARGET_PLATFORM: rockchip
      TARGET_SUBPLATFORM: rk35xx
      FIRMWARE_DIST: istoreos
      ISTOREOS_BRANCH: "istoreos-24.10"
      LOCAL_BUILD_DIR: "${{ github.workspace }}/build"
      VENV_PATH: "${LOCAL_BUILD_DIR}/python-venv"

    steps:
      - name: 1. 拉取仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 2. 系统依赖+Python虚拟环境配置（确保git安装）
        run: |
          echo "===== 安装系统基础依赖（含git） ====="
          # 明确包含git，确保被安装
          REQUIRED_PACKAGES="build-essential flex bison g++ gawk gcc-multilib \
            gettext git  # 强制包含git
            libncurses5-dev libssl-dev libelf-dev python3 python3-pip \
            python3-venv rsync unzip wget zlib1g-dev quilt u-boot-tools squashfs-tools \
            meson ninja-build cmake device-tree-compiler liblz4-tool"

          # 安装缺失的依赖（重点检查git）
          for pkg in $REQUIRED_PACKAGES; do
            if ! dpkg -l | grep -q "$pkg"; then
              echo "安装缺失依赖：$pkg"
              # 强制更新并安装，避免依赖冲突
              sudo apt update -y || sudo apt update -y  # 重试更新
              sudo apt install -y "$pkg" || {
                echo "ERROR: 安装 $pkg 失败！"
                exit 1
              }
            fi
          done

          # 单独验证git是否安装成功（核心修复点）
          echo "===== 验证git是否可用 ====="
          if ! command -v git &> /dev/null; then
            echo "ERROR: git 未安装成功！手动重试安装..."
            sudo apt install -y git --reinstall
            # 再次验证，失败则终止
            if ! command -v git &> /dev/null; then
              echo "ERROR: git 始终安装失败，请手动检查系统包管理器！"
              exit 1
            fi
          fi

          echo "===== 创建Python虚拟环境 ====="
          if [ -d "$VENV_PATH" ]; then
            rm -rf "$VENV_PATH"
          fi
          python3 -m venv "$VENV_PATH"
          if [ ! -f "$VENV_PATH/bin/activate" ]; then
            echo "ERROR: 虚拟环境创建失败！"
            exit 1
          fi

          echo "===== 安装Python依赖 ====="
          source "$VENV_PATH/bin/activate"
          if ! python3 -c "import elftools" &> /dev/null; then
            pip install pyelftools --upgrade
          fi
          if ! python3 -c "import elftools" &> /dev/null; then
            echo "ERROR: pyelftools安装失败！"
            exit 1
          fi
          deactivate

          echo "===== 验证核心工具 ====="
          # 明确包含git的验证
          REQUIRED_TOOLS="gcc make python3 git wget unzip mksquashfs"
          for tool in $REQUIRED_TOOLS; do
            if ! command -v $tool &> /dev/null; then
              echo "ERROR: 核心工具 $tool 未安装！"
              exit 1
            fi
          done

      - name: 3. 缓存编译资源
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.LOCAL_BUILD_DIR }}/${{ env.FIRMWARE_DIST }}/dl
            ${{ env.LOCAL_BUILD_DIR }}/${{ env.FIRMWARE_DIST }}/feeds
          key: ${{ runner.os }}-istoreos-${{ env.ISTOREOS_BRANCH }}-${{ hashFiles('xgp-qmodem.config') }}
          restore-keys: |
            ${{ runner.os }}-istoreos-${{ env.ISTOREOS_BRANCH }}-

      - name: 4. 克隆/更新iStoreOS稳定分支（依赖git）
        run: |
          mkdir -p ${{ env.LOCAL_BUILD_DIR }}
          cd ${{ env.LOCAL_BUILD_DIR }}

          if [ ! -d "${{ env.FIRMWARE_DIST }}" ]; then
            # 显式使用git克隆，确保命令可用
            git clone https://github.com/istoreos/istoreos.git ${{ env.FIRMWARE_DIST }} || {
              echo "ERROR: git克隆失败，请检查网络或git安装！"
              exit 1
            }
          fi
          cd ${{ env.FIRMWARE_DIST }}
          git checkout ${{ env.ISTOREOS_BRANCH }}
          git pull  # 拉取最新代码

          echo "当前分支：$(git branch --show-current)"
          echo "最新Commit：$(git rev-parse --short HEAD)"

      - name: 5. 同步软件源
        run: |
          cd ${{ env.LOCAL_BUILD_DIR }}/${{ env.FIRMWARE_DIST }}
          sed -i 's#https://downloads.openwrt.org#https://mirrors.ustc.edu.cn/openwrt#g' feeds.conf.default
          sed -i 's#https://mirrors.cernet.edu.cn#https://mirrors.ustc.edu.cn#g' feeds.conf.default

          if ! grep -q "qmodem" feeds.conf.default; then
            echo "src-git qmodem https://github.com/FUjr/QModem.git" >> feeds.conf.default
          fi

          ./scripts/feeds update -a
          ./scripts/feeds install -a -f

      - name: 6. 导入设备配置文件
        run: |
          cd ${{ env.LOCAL_BUILD_DIR }}/${{ env.FIRMWARE_DIST }}
          cp ${{ github.workspace }}/xgp-qmodem.config .config
          make defconfig

          if ! grep -q "CONFIG_TARGET_rockchip=y" .config; then
            echo "ERROR: 平台配置错误！"
            exit 1
          fi
          if ! grep -q "CONFIG_PACKAGE_luci-app-qmodem=y" .config; then
            echo "ERROR: QModem未启用！"
            exit 1
          fi

      - name: 7. 本地多核编译
        run: |
          cd ${{ env.LOCAL_BUILD_DIR }}/${{ env.FIRMWARE_DIST }}
          source "$VENV_PATH/bin/activate"
          if [ "$(which python3)" != "$VENV_PATH/bin/python3" ]; then
            echo "ERROR: 虚拟环境激活失败！"
            exit 1
          fi

          CPU_CORES=$(nproc)
          echo "使用 $CPU_CORES 核心编译..."

          timeout 180m bash -c "
            make -j$CPU_CORES V=m 2>&1 | tee build.log &
            PID=\$!
            while kill -0 \$PID 2>/dev/null; do
              echo \"===== 编译中（$(date +%H:%M:%S)）=====\"
              grep -E \"Compiling|Linking|Installing\" build.log | tail -5
              sleep 600
            done
            wait \$PID
          "

          deactivate

          FIRMWARE_DIR="bin/targets/$TARGET_PLATFORM/$TARGET_SUBPLATFORM"
          if [ ! -d "$FIRMWARE_DIR" ] || [ -z "$(ls $FIRMWARE_DIR/*.sysupgrade.bin 2>/dev/null)" ]; then
            echo "ERROR: 编译失败！最后1000行日志："
            cat build.log | tail -1000
            exit 1
          fi
          echo "固件编译成功！"

      - name: 8. 打包产物
        run: |
          LOCAL_OUTPUT="${{ github.workspace }}/local-firmware"
          mkdir -p $LOCAL_OUTPUT
          REMOTE_OUTPUT="${{ env.LOCAL_BUILD_DIR }}/output"
          mkdir -p $REMOTE_OUTPUT

          FIRMWARE_DIR="${{ env.LOCAL_BUILD_DIR }}/${{ env.FIRMWARE_DIST }}/bin/targets/$TARGET_PLATFORM/$TARGET_SUBPLATFORM"
          cp $FIRMWARE_DIR/*.sysupgrade.bin $LOCAL_OUTPUT/
          cp $FIRMWARE_DIR/*.factory.img $LOCAL_OUTPUT/ 2>/dev/null
          cp ${{ env.LOCAL_BUILD_DIR }}/${{ env.FIRMWARE_DIST }}/.config $LOCAL_OUTPUT/final_config.config
          cp ${{ env.LOCAL_BUILD_DIR }}/${{ env.FIRMWARE_DIST }}/build.log $LOCAL_OUTPUT/build_log.txt

          cp -r $LOCAL_OUTPUT/* $REMOTE_OUTPUT/
          echo "本地产物路径：$LOCAL_OUTPUT"
          ls -l $LOCAL_OUTPUT

      - name: 9. 上传产物到GitHub
        uses: actions/upload-artifact@v4
        with:
          name: istoreos-local-final
          path: ${{ env.LOCAL_BUILD_DIR }}/output/
          retention-days: 30
