name: 本地编译iStoreOS-XGP（QModem依赖修复）

on:
  workflow_dispatch:

jobs:
  local-build:
    runs-on: self-hosted
    env:
      TARGET_PLATFORM: rockchip
      TARGET_SUBPLATFORM: rk35xx
      FIRMWARE_DIST: istoreos
      ISTOREOS_BRANCH: "istoreos-24.10"
      LOCAL_BUILD_DIR: "${{ github.workspace }}/build"
      VENV_PATH: "${LOCAL_BUILD_DIR}/python-venv"
      GITHUB_MIRROR: "https://bgithub.xyz"

    steps:
      - name: 0. 配置GitHub镜像
        run: |
          git config --global url."${{ env.GITHUB_MIRROR }}/".insteadOf "https://github.com/"

      - name: 1. 拉取仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 2. 安装系统依赖
        run: |
          echo "===== 安装核心系统依赖 ====="
          REQUIRED_PACKAGES="build-essential flex bison g++ gawk gcc-multilib \
            gettext git libncurses5-dev libssl-dev libelf-dev python3 python3-pip \
            python3-venv rsync unzip wget zlib1g-dev quilt u-boot-tools squashfs-tools \
            meson ninja-build cmake device-tree-compiler liblz4-tool \
            swig python3-dev python3-setuptools libncursesw5-dev"

          for pkg in $REQUIRED_PACKAGES; do
            if [ -z "$pkg" ] || [ "$pkg" = "\\" ]; then continue; fi
            if ! dpkg -l | grep -q "$pkg"; then
              echo "安装缺失依赖：$pkg"
              sudo apt update -y
              sudo apt install -y "$pkg" || exit 1
            fi
          done

          if ! command -v swig &> /dev/null; then
            echo "ERROR: swig安装失败！"
            exit 1
          fi

      - name: 3. 配置Python虚拟环境
        run: |
          echo "===== 准备虚拟环境 ====="
          mkdir -p "$(dirname ${{ env.VENV_PATH }})"
          rm -rf "${{ env.VENV_PATH }}"
          /usr/bin/python3 -m venv "${{ env.VENV_PATH }}" || exit 1

          source "${{ env.VENV_PATH }}/bin/activate" || exit 1
          pip install pyelftools --upgrade || exit 1
          if ! python3 -c "import elftools" &> /dev/null; then
            echo "ERROR: pyelftools缺失！"
            exit 1
          fi
          deactivate

      - name: 4. 克隆iStoreOS源码
        run: |
          mkdir -p ${{ env.LOCAL_BUILD_DIR }}
          cd ${{ env.LOCAL_BUILD_DIR }}
          rm -rf ${{ env.FIRMWARE_DIST }}
          git clone "${{ env.GITHUB_MIRROR }}/istoreos/istoreos.git" ${{ env.FIRMWARE_DIST }} || exit 1
          cd ${{ env.FIRMWARE_DIST }}
          git checkout ${{ env.ISTOREOS_BRANCH }} || exit 1
          git pull || exit 1

      - name: 5. 同步QModem源（适配实际包名）
        run: |
          cd ${{ env.LOCAL_BUILD_DIR }}/${{ env.FIRMWARE_DIST }}
          # 替换国内源加速
          sed -i 's#https://downloads.openwrt.org#https://mirrors.ustc.edu.cn/openwrt#g' feeds.conf.default

          # 清理旧QModem源并添加官方源
          sed -i '/qmodem/d' feeds.conf.default
          echo "src-git qmodem https://github.com/FUjr/QModem.git" >> feeds.conf.default

          # 强制同步并安装（显示详细日志，便于排查）
          echo "===== 同步QModem源 ====="
          ./scripts/feeds update -a -f -v || exit 1  # -v显示详细同步日志
          echo "===== 安装QModem包 ====="
          ./scripts/feeds install -a -f -v || exit 1  # -v显示安装详情

          # 关键修复：适配QModem源实际包名（可能使用下划线而非连字符）
          echo "===== 列出QModem源中的包 ====="
          ls -l package/feeds/qmodem/  # 输出实际包名，便于调试

          # 检查实际存在的依赖包（根据日志，可能是quectel_CM_5G_M等）
          REQUIRED_QMODEM_PACKAGES=(
            "quectel_CM_5G_M"  # 日志中出现的包名（下划线）
            "quectel_MHI"      # 确认存在的包
            "qfirehose"
          )
          for pkg in "${REQUIRED_QMODEM_PACKAGES[@]}"; do
            if [ ! -d "package/feeds/qmodem/$pkg" ]; then
              echo "ERROR: QModem依赖包 $pkg 未同步！"
              exit 1
            fi
          done

      - name: 6. 导入设备配置（适配QModem实际依赖）
        run: |
          cd ${{ env.LOCAL_BUILD_DIR }}/${{ env.FIRMWARE_DIST }}
          cp ${{ github.workspace }}/xgp-qmodem.config .config

          # 修正配置中依赖的包名（连字符→下划线，匹配源实际包名）
          sed -i 's/quectel-CM-5G/quectel_CM_5G_M/g' .config
          sed -i 's/quectel-cm/quectel_CM_5G_M/g' .config  # 用实际存在的包替代

          make defconfig || exit 1

      - name: 7. 编译
        run: |
          cd ${{ env.LOCAL_BUILD_DIR }}/${{ env.FIRMWARE_DIST }}
          source "${{ env.VENV_PATH }}/bin/activate" || exit 1
          make prereq || exit 1

          CPU_CORES=$(nproc)
          make -j$CPU_CORES V=m 2>&1 | tee build.log &
          PID=$!
          sleep 60
          while kill -0 $PID 2>/dev/null; do
            echo "===== 编译中（$(date +%H:%M:%S)）====="
            grep -E "Compiling|Linking|Installing" build.log | tail -5
            sleep 600
          done
          wait $PID

          deactivate
          FIRMWARE_DIR="bin/targets/$TARGET_PLATFORM/$TARGET_SUBPLATFORM"
          if [ ! -d "$FIRMWARE_DIR" ] || [ -z "$(ls $FIRMWARE_DIR/*.sysupgrade.bin 2>/dev/null)" ]; then
            cat build.log | tail -1000
            exit 1
          fi

      - name: 8. 打包产物
        run: |
          LOCAL_OUTPUT="${{ github.workspace }}/local-firmware"
          mkdir -p $LOCAL_OUTPUT
          cp -r ${{ env.LOCAL_BUILD_DIR }}/${{ env.FIRMWARE_DIST }}/bin/targets/$TARGET_PLATFORM/$TARGET_SUBPLATFORM/* $LOCAL_OUTPUT/
          cp ${{ env.LOCAL_BUILD_DIR }}/${{ env.FIRMWARE_DIST }}/build.log $LOCAL_OUTPUT/
          echo "产物路径：$LOCAL_OUTPUT"
